#include "ActionDefinition.h"

QList<ActionDefinition> allActionDefinitions()
{
    return {
        // ── Editor: Clipboard ──
        {Editor::Cut,
         QStringLiteral("editor.cut"),
         QStringLiteral("Cut"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+X")),
         Design::Icon::Cut,
         ButtonId::Cut,
         false,
         false,
         1,
         10},
        {Editor::Copy,
         QStringLiteral("editor.copy"),
         QStringLiteral("Copy"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+C")),
         Design::Icon::Copy,
         ButtonId::Copy,
         false,
         false,
         1,
         11},
        {Editor::Paste,
         QStringLiteral("editor.paste"),
         QStringLiteral("Paste"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+V")),
         Design::Icon::Paste,
         ButtonId::Paste,
         false,
         false,
         1,
         12},

        // ── Editor: History ──
        {Editor::Undo,
         QStringLiteral("editor.undo"),
         QStringLiteral("Undo"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+Z")),
         Design::Icon::Undo,
         ButtonId::Undo,
         false,
         false,
         2,
         20},
        {Editor::Redo,
         QStringLiteral("editor.redo"),
         QStringLiteral("Redo"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+Shift+Z")),
         Design::Icon::Redo,
         ButtonId::Redo,
         false,
         false,
         2,
         21},

        // ── Editor: Formatting ──
        {Editor::Bold,
         QStringLiteral("editor.bold"),
         QStringLiteral("Bold"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+B")),
         Design::Icon::Bold,
         ButtonId::Bold,
         true,
         false,
         4,
         30},
        {Editor::Italic,
         QStringLiteral("editor.italic"),
         QStringLiteral("Italic"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+I")),
         Design::Icon::Italic,
         ButtonId::Italic,
         true,
         false,
         4,
         31},
        {Editor::Underline,
         QStringLiteral("editor.underline"),
         QStringLiteral("Underline"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+U")),
         Design::Icon::Underline,
         ButtonId::Underline,
         true,
         false,
         4,
         32},
        {Editor::Strikethrough,
         QStringLiteral("editor.strikethrough"),
         QStringLiteral("Strikethrough"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+Shift+S")),
         Design::Icon::Strikethrough,
         ButtonId::Strike,
         true,
         false,
         4,
         33},
        {Editor::ClearFormat,
         QStringLiteral("editor.clearFormat"),
         QStringLiteral("Clear Formatting"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+Space")),
         Design::Icon::ClearFormat,
         ButtonId::ClearFormat,
         false,
         false,
         4,
         34},

        // ── Editor: Find ──
        {Editor::Find,
         QStringLiteral("editor.find"),
         QStringLiteral("Find"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+F")),
         Design::Icon::Search,
         ButtonId::Find,
         true,
         false,
         3,
         40},
        {Editor::FindNext,
         QStringLiteral("editor.findNext"),
         QStringLiteral("Find Next"),
         QStringLiteral("Editor"),
         QKeySequence(Qt::Key_F3),
         Design::Icon::Search,
         ButtonId::None,
         false,
         false,
         -1,
         41},
        {Editor::FindPrev,
         QStringLiteral("editor.findPrev"),
         QStringLiteral("Find Previous"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Shift+F3")),
         Design::Icon::Search,
         ButtonId::None,
         false,
         false,
         -1,
         42},

        // ── Editor: Zoom ──
        {Editor::ZoomIn,
         QStringLiteral("editor.zoomIn"),
         QStringLiteral("Zoom In"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl++")),
         Design::Icon::ZoomIn,
         ButtonId::ZoomIn,
         false,
         false,
         -1,
         50},
        {Editor::ZoomOut,
         QStringLiteral("editor.zoomOut"),
         QStringLiteral("Zoom Out"),
         QStringLiteral("Editor"),
         QKeySequence(QStringLiteral("Ctrl+-")),
         Design::Icon::ZoomOut,
         ButtonId::ZoomOut,
         false,
         false,
         -1,
         51},

        // ── Note ──
        {Notes::New,
         QStringLiteral("note.new"),
         QStringLiteral("New Note"),
         QStringLiteral("Note"),
         QKeySequence(QStringLiteral("Ctrl+N")),
         Design::Icon::New,
         ButtonId::New,
         false,
         false,
         0,
         10},
        {Notes::Delete,
         QStringLiteral("note.delete"),
         QStringLiteral("Delete Note"),
         QStringLiteral("Note"),
         QKeySequence(QStringLiteral("Ctrl+Shift+Delete")),
         Design::Icon::Delete,
         ButtonId::Delete,
         false,
         false,
         0,
         11},
        {Notes::Lock,
         QStringLiteral("note.lock"),
         QStringLiteral("Toggle Lock"),
         QStringLiteral("Note"),
         QKeySequence(QStringLiteral("Ctrl+L")),
         Design::Icon::Lock,
         ButtonId::None,
         false,
         false,
         -1,
         20},
        {Notes::Ontop,
         QStringLiteral("note.ontop"),
         QStringLiteral("Always on Top"),
         QStringLiteral("Note"),
         QKeySequence(QStringLiteral("Ctrl+Shift+T")),
         Design::Icon::Ontop,
         ButtonId::Ontop,
         true,
         false,
         5,
         30},
        {Notes::ToolbarToggle,
         QStringLiteral("note.toolbarToggle"),
         QStringLiteral("Toggle Toolbar"),
         QStringLiteral("Note"),
         QKeySequence(QStringLiteral("Ctrl+Shift+H")),
         Design::Icon::Tool,
         ButtonId::None,
         false,
         false,
         -1,
         40},
        {Notes::Hide,
         QStringLiteral("note.hide"),
         QStringLiteral("Hide Note"),
         QStringLiteral("Note"),
         QKeySequence(),
         Design::Icon::HideNote,
         ButtonId::HideNote,
         false,
         false,
         0,
         50},
        {Notes::HideAll,
         QStringLiteral("note.hideAll"),
         QStringLiteral("Hide All Notes"),
         QStringLiteral("Note"),
         QKeySequence(),
         Design::Icon::HideAllNotes,
         ButtonId::HideAllNotes,
         false,
         false,
         0,
         51},
        {Notes::Prefs,
         QStringLiteral("note.prefs"),
         QStringLiteral("Preferences"),
         QStringLiteral("Note"),
         QKeySequence(),
         Design::Icon::Settings,
         ButtonId::Prefs,
         false,
         true,
         6,
         60},

        // ── Global ──
        {Global::ToggleNotes,
         QStringLiteral("global.toggleNotes"),
         QStringLiteral("Show/Hide All Notes"),
         QStringLiteral("Global"),
         QKeySequence(QStringLiteral("Ctrl+Alt+N")),
         Design::Icon::HideShowNote,
         ButtonId::None,
         false,
         false,
         -1,
         10},
        {Global::QuickCapture,
         QStringLiteral("global.quickCapture"),
         QStringLiteral("Quick Note"),
         QStringLiteral("Global"),
         QKeySequence(QStringLiteral("Ctrl+Shift+Space")),
         Design::Icon::QuickNote,
         ButtonId::None,
         false,
         false,
         -1,
         20},
        {Global::GhostMode,
         QStringLiteral("global.ghostMode"),
         QStringLiteral("Toggle Ghost Mode"),
         QStringLiteral("Global"),
         QKeySequence(QStringLiteral("Ctrl+Alt+G")),
         Design::Icon::Ghost,
         ButtonId::None,
         false,
         false,
         -1,
         30},
    };
}
